version: '3.8'
services:
  db:
    image: postgres:15
    container_name: ak_db
    environment:
      POSTGRES_DB: asiankitchen
      POSTGRES_USER: localuser
      POSTGRES_PASSWORD: localpass
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: