package ch.asiankitchen.model;

public enum Status {
    ORDER_NEW,
    ORDER_CONFIRMED,
    ORDER_PREPARING,
    ORDER_OTW,
    ORDER_DELIVERED,
    RESERVATION_REQUEST_SENT,
    RESERVATION_REQUEST_CONFIRMED,
    RESERVATION_REQUEST_REJECTED
}
